### ISSUE TITLE
ReliableDNSClient contract

### ISSUE THREAD

**Issue by arnt** [rtreffer/minidns#33]
It's a fine class, but it would be finer with a bit of a specified contract. What does reliable mean? What can I rely on?

Ideally I'd like to have the following:
1. If there is a signed answer for the query, then I'll get that, even if the ISP's cache isn't friendly.
2. If there is an answer, but not signed, then I'll get that.
3. I can tell the difference.

**Comment by Flowdalic** [comment]
> It's a fine class,

Thanks :)

> Ideally I'd like to have the following:

I'm not sure if you are suggesting that ReliableDNSClient should get some more javadoc or that the code should be changed.

As far as I can tell ReliableDNSClient could return an answer without DNSSEC RR even if they are out there. It's hard (or even impossible) to prevent an attacker from forging fake responses with DNSSEC data stripped and/or otherwise manipulated. So I guess you want us to put 3. in the class's javadoc to clarify the contract the API provides?

The "reliable" in the class's name referss to the client using the system's forward resolvers first, optionally falling back to performing an iterative resolution (e.g. in case the forward resolvers do not support large answers which are common with DNSSEC).

**Comment by arnt** [comment]
I'm not sure whether more doc suffices. My guess is "mostly", but I don't see any way to ask "was this answer signed or not?" so a little code seems necessary.

(Minidns should perhaps switch to iterative resolving if the forwarding resolver doesn't return DNSSEC records for domain names where that's known to exist, such as the root and a dozen or two TLDs.)

**Comment by Flowdalic** [comment]
> but I don't see any way to ask "was this answer signed or not?" so a little code seems necessary.

This is done in DNSSECClient.queryDnssec(): The ad flag will be set in the answer if it was verified.

> (Minidns should perhaps switch to iterative resolving if the forwarding resolver doesn't return DNSSEC records for domain names where that's known to exist, such as the root and a dozen or two TLDs.)

I feat that this gains you nothing and only add complexity to the API and code.

**Comment by Flowdalic** [comment]
After thinking a bit about it and discussing it with Marvin, I came up with https://github.com/Flowdalic/minidns/commit/951dd9a37d4e5163ec609afe5ae8899763069d60

It should improve the situation, at least for resolvers like 81.218.119.11, which are not DNSSEC aware and thus do not return answers with the DO flag set. This commit is not completely tested, so please view it as a draft for now.

**Comment by Flowdalic** [comment]
This issue is related to #40. I will probably write some documentation about best practices regarding "reliable" DNSSEC queries with MiniDNS.

**Comment by Flowdalic** [comment]
Closed in favor of #40
